-- File generated by the BNF Converter (bnfc 2.9.4).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Janeklang.

module Janeklang.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Janeklang.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Janeklang.Abs.Ident where
  prt _ (Janeklang.Abs.Ident i) = doc $ showString i
instance Print (Janeklang.Abs.Program' a) where
  prt i = \case
    Janeklang.Abs.PProg _ topdefs -> prPrec i 0 (concatD [prt 0 topdefs])

instance Print (Janeklang.Abs.TopDef' a) where
  prt i = \case
    Janeklang.Abs.PFnDef _ type_ id_ args block -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])
    Janeklang.Abs.PVarDef _ type_ id_ expr -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])

instance Print [Janeklang.Abs.TopDef' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (Janeklang.Abs.Arg' a) where
  prt i = \case
    Janeklang.Abs.PAr _ type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_])
    Janeklang.Abs.PArRef _ type_ id_ -> prPrec i 0 (concatD [doc (showString "ref"), prt 0 type_, prt 0 id_])

instance Print [Janeklang.Abs.Arg' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Janeklang.Abs.Block' a) where
  prt i = \case
    Janeklang.Abs.SBlk _ stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print [Janeklang.Abs.Stmt' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (Janeklang.Abs.Stmt' a) where
  prt i = \case
    Janeklang.Abs.SEmpty _ -> prPrec i 0 (concatD [doc (showString ";")])
    Janeklang.Abs.SBStmt _ block -> prPrec i 0 (concatD [prt 0 block])
    Janeklang.Abs.SAss _ id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])
    Janeklang.Abs.SRet _ expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    Janeklang.Abs.SVRet _ -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    Janeklang.Abs.SCond _ expr block -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block])
    Janeklang.Abs.SCondElse _ expr block1 block2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block1, doc (showString "else"), prt 0 block2])
    Janeklang.Abs.SWhile _ expr block -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block])
    Janeklang.Abs.SExp _ expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])
    Janeklang.Abs.SNestedFnDef _ topdef -> prPrec i 0 (concatD [prt 0 topdef])
    Janeklang.Abs.SBreak _ -> prPrec i 0 (concatD [doc (showString "break")])
    Janeklang.Abs.SContinue _ -> prPrec i 0 (concatD [doc (showString "continue")])
    Janeklang.Abs.SPrint _ expr -> prPrec i 0 (concatD [doc (showString "print"), doc (showString "("), prt 0 expr, doc (showString ")"), doc (showString ";")])

instance Print (Janeklang.Abs.Type' a) where
  prt i = \case
    Janeklang.Abs.TInt _ -> prPrec i 0 (concatD [doc (showString "int")])
    Janeklang.Abs.TStr _ -> prPrec i 0 (concatD [doc (showString "string")])
    Janeklang.Abs.TBool _ -> prPrec i 0 (concatD [doc (showString "bool")])
    Janeklang.Abs.TVoid _ -> prPrec i 0 (concatD [doc (showString "void")])
    Janeklang.Abs.Fun _ type_ types -> prPrec i 0 (concatD [prt 0 type_, doc (showString "("), prt 0 types, doc (showString ")")])

instance Print [Janeklang.Abs.Type' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Janeklang.Abs.Expr' a) where
  prt i = \case
    Janeklang.Abs.EVar _ id_ -> prPrec i 6 (concatD [prt 0 id_])
    Janeklang.Abs.ELitInt _ n -> prPrec i 6 (concatD [prt 0 n])
    Janeklang.Abs.ELitTrue _ -> prPrec i 6 (concatD [doc (showString "true")])
    Janeklang.Abs.ELitFalse _ -> prPrec i 6 (concatD [doc (showString "false")])
    Janeklang.Abs.EApp _ id_ exprs -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 exprs, doc (showString ")")])
    Janeklang.Abs.EString _ str -> prPrec i 6 (concatD [printString str])
    Janeklang.Abs.ENeg _ expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    Janeklang.Abs.ENot _ expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    Janeklang.Abs.EMul _ expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    Janeklang.Abs.EAdd _ expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    Janeklang.Abs.ERel _ expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    Janeklang.Abs.EAnd _ expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    Janeklang.Abs.EOr _ expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])

instance Print [Janeklang.Abs.Expr' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Janeklang.Abs.AddOp' a) where
  prt i = \case
    Janeklang.Abs.OPlus _ -> prPrec i 0 (concatD [doc (showString "+")])
    Janeklang.Abs.OMinus _ -> prPrec i 0 (concatD [doc (showString "-")])

instance Print (Janeklang.Abs.MulOp' a) where
  prt i = \case
    Janeklang.Abs.OTimes _ -> prPrec i 0 (concatD [doc (showString "*")])
    Janeklang.Abs.ODiv _ -> prPrec i 0 (concatD [doc (showString "/")])
    Janeklang.Abs.OMod _ -> prPrec i 0 (concatD [doc (showString "%")])

instance Print (Janeklang.Abs.RelOp' a) where
  prt i = \case
    Janeklang.Abs.OLTH _ -> prPrec i 0 (concatD [doc (showString "<")])
    Janeklang.Abs.OLE _ -> prPrec i 0 (concatD [doc (showString "<=")])
    Janeklang.Abs.OGTH _ -> prPrec i 0 (concatD [doc (showString ">")])
    Janeklang.Abs.OGE _ -> prPrec i 0 (concatD [doc (showString ">=")])
    Janeklang.Abs.OEQU _ -> prPrec i 0 (concatD [doc (showString "==")])
    Janeklang.Abs.ONE _ -> prPrec i 0 (concatD [doc (showString "!=")])
