# Generated by Django 4.2.1 on 2023-05-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_file_owner_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
