# Generated by Django 4.2.1 on 2023-05-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_file_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='text',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
