#!/bin/bash
# Generated by ChatGPT
# Check if exactly one argument is provided
if [ "$#" -ne 1 ]; then
    echo "Usage: ./run_test <file_path>"
    exit 1
fi

# Define the interpreter path
INTERPRETER_PATH="./dist-newstyle/build/x86_64-linux/ghc-9.0.2/janeklang-0.1.0.0/x/janeklang/build/janeklang/janeklang"

# Get the file path from the argument
FILE_PATH=$1

# Check if the input file exists
if [ ! -f "$FILE_PATH" ]; then
    echo "Error: Input file does not exist."
    exit 1
fi

# Define the output and error file names
OUT_FILE="${FILE_PATH%.*}.out"
ERR_FILE="${FILE_PATH%.*}.err"

# Check if output file exists, create if it does not
if [ ! -f "$OUT_FILE" ]; then
    echo "Creating $OUT_FILE because it does not exist."
    touch "$OUT_FILE"
fi

# Check if error file exists, create if it does not
if [ ! -f "$ERR_FILE" ]; then
    echo "Creating $ERR_FILE because it does not exist."
    touch "$ERR_FILE"
fi

# Run the interpreter and capture the outputs
$INTERPRETER_PATH "$FILE_PATH" > "$OUT_FILE" 2> "$ERR_FILE"
